$include:
  - conf/final/24khz.yml

# Model setup
FlowMatching.n_mels: 100
FlowMatching.in_dim: 64
FlowMatching.dim: 512
FlowMatching.num_layers: 8
FlowMatching.mel_enc_num_layers: 4
FlowMatching.drop_path_rate: 0.0

MelSpectrogram.sample_rate: 24000
MelSpectrogram.n_fft: 1024
MelSpectrogram.hop_length: 256
MelSpectrogram.n_mels: 100
MelSpectrogram.power: 2
MelSpectrogram.center: False

dac_path: outputs/dac/weights.pth

AdamW.lr: 0.0005
batch_size: 256
train/AudioDataset.duration: 1.0
num_iters: 400000
save_iters: [10000, 50000, 100000, 200000]
valid_freq: 1000
sample_freq: 10000

train/build_dataset.folders:
  speech_libritts:
    - download/LibriTTS/train-clean-100
    - download/LibriTTS/train-clean-360
    - download/LibriTTS/train-other-500

val/build_dataset.folders:
  speech_libritts:
    - download/LibriTTS/dev-clean
    - download/LibriTTS/dev-other

test/build_dataset.folders:
  speech_libritts:
    - download/LibriTTS/test-clean
    - download/LibriTTS/test-other
